import type { LocalizedString, TranslatedLocale } from "./locales";
// Columns: seven commands, counter name, optional description, replacement name.
type TranslationRow = readonly [string, string, string, string, string, string, string, string, string, string];
const rows = {
  en: ["Create a counter or restore a removed counter", "Remove a counter without losing its count", "Rename a counter", "Show a counter's count and description", "List the counters here", "Increase a counter by one", "Decrease a counter by one", "Counter name (letters and digits only)", "Optional description for the counter", "New counter name (letters and digits only)"],
  id: ["Buat penghitung atau pulihkan yang dihapus", "Hapus penghitung tanpa kehilangan nilainya", "Ubah nama penghitung", "Lihat nilai dan deskripsi penghitung", "Daftar penghitung di sini", "Tambah nilai penghitung satu", "Kurangi nilai penghitung satu", "Nama penghitung (hanya huruf dan angka)", "Deskripsi opsional penghitung", "Nama baru penghitung (hanya huruf dan angka)"],
  da: ["Opret en tæller eller gendan en fjernet tæller", "Fjern en tæller uden at miste dens tal", "Omdøb en tæller", "Vis en tællers tal og beskrivelse", "Vis tællerne her", "Forøg en tæller med én", "Formindsk en tæller med én", "Tællernavn (kun bogstaver og tal)", "Valgfri beskrivelse af tælleren", "Nyt tællernavn (kun bogstaver og tal)"],
  de: ["Einen Zähler erstellen oder wiederherstellen", "Einen Zähler entfernen und seinen Stand behalten", "Einen Zähler umbenennen", "Zählerstand und Beschreibung anzeigen", "Die Zähler hier auflisten", "Einen Zähler um eins erhöhen", "Einen Zähler um eins verringern", "Zählername (nur Buchstaben und Ziffern)", "Optionale Beschreibung des Zählers", "Neuer Zählername (nur Buchstaben und Ziffern)"],
  "es-ES": ["Crear un contador o restaurar uno eliminado", "Eliminar un contador sin perder su valor", "Cambiar el nombre de un contador", "Mostrar el valor y la descripción de un contador", "Listar los contadores de aquí", "Aumentar un contador en uno", "Disminuir un contador en uno", "Nombre del contador (solo letras y números)", "Descripción opcional del contador", "Nuevo nombre del contador (solo letras y números)"],
  "es-419": ["Crear un contador o restaurar uno eliminado", "Eliminar un contador sin perder su valor", "Cambiar el nombre de un contador", "Mostrar el valor y la descripción de un contador", "Listar los contadores de aquí", "Incrementar un contador en uno", "Reducir un contador en uno", "Nombre del contador (solo letras y números)", "Descripción opcional del contador", "Nuevo nombre del contador (solo letras y números)"],
  fr: ["Créer un compteur ou restaurer un compteur supprimé", "Supprimer un compteur sans perdre sa valeur", "Renommer un compteur", "Afficher la valeur et la description d'un compteur", "Lister les compteurs ici", "Augmenter un compteur de un", "Diminuer un compteur de un", "Nom du compteur (lettres et chiffres uniquement)", "Description facultative du compteur", "Nouveau nom du compteur (lettres et chiffres uniquement)"],
  hr: ["Stvori brojač ili vrati uklonjeni brojač", "Ukloni brojač bez gubitka njegove vrijednosti", "Preimenuj brojač", "Prikaži vrijednost i opis brojača", "Prikaži ovdašnje brojače", "Povećaj brojač za jedan", "Smanji brojač za jedan", "Naziv brojača (samo slova i znamenke)", "Neobavezan opis brojača", "Novi naziv brojača (samo slova i znamenke)"],
  it: ["Crea un contatore o ripristinane uno rimosso", "Rimuovi un contatore senza perderne il valore", "Rinomina un contatore", "Mostra il valore e la descrizione di un contatore", "Elenca i contatori qui", "Aumenta un contatore di uno", "Diminuisci un contatore di uno", "Nome del contatore (solo lettere e cifre)", "Descrizione facoltativa del contatore", "Nuovo nome del contatore (solo lettere e cifre)"],
  lt: ["Sukurti skaitiklį arba atkurti pašalintą skaitiklį", "Pašalinti skaitiklį neprarandant jo reikšmės", "Pervadinti skaitiklį", "Rodyti skaitiklio reikšmę ir aprašą", "Rodyti čia esančius skaitiklius", "Padidinti skaitiklį vienetu", "Sumažinti skaitiklį vienetu", "Skaitiklio pavadinimas (tik raidės ir skaitmenys)", "Neprivalomas skaitiklio aprašas", "Naujas skaitiklio pavadinimas (tik raidės ir skaitmenys)"],
  hu: ["Számláló létrehozása vagy eltávolított számláló visszaállítása", "Számláló eltávolítása az értéke megőrzésével", "Számláló átnevezése", "Számláló értékének és leírásának megjelenítése", "Az itteni számlálók listázása", "Számláló növelése eggyel", "Számláló csökkentése eggyel", "Számláló neve (csak betűk és számjegyek)", "A számláló nem kötelező leírása", "Számláló új neve (csak betűk és számjegyek)"],
  nl: ["Maak een teller of herstel een verwijderde teller", "Verwijder een teller zonder de stand te verliezen", "Hernoem een teller", "Toon de stand en beschrijving van een teller", "Toon de tellers hier", "Verhoog een teller met één", "Verlaag een teller met één", "Tellernaam (alleen letters en cijfers)", "Optionele beschrijving van de teller", "Nieuwe tellernaam (alleen letters en cijfers)"],
  no: ["Opprett en teller eller gjenopprett en fjernet teller", "Fjern en teller uten å miste verdien", "Gi en teller nytt navn", "Vis en tellers verdi og beskrivelse", "Vis tellerne her", "Øk en teller med én", "Reduser en teller med én", "Tellernavn (bare bokstaver og tall)", "Valgfri beskrivelse av telleren", "Nytt tellernavn (bare bokstaver og tall)"],
  pl: ["Utwórz licznik lub przywróć usunięty licznik", "Usuń licznik bez utraty jego wartości", "Zmień nazwę licznika", "Pokaż wartość i opis licznika", "Wyświetl tutejsze liczniki", "Zwiększ licznik o jeden", "Zmniejsz licznik o jeden", "Nazwa licznika (tylko litery i cyfry)", "Opcjonalny opis licznika", "Nowa nazwa licznika (tylko litery i cyfry)"],
  "pt-BR": ["Criar um contador ou restaurar um removido", "Remover um contador sem perder seu valor", "Renomear um contador", "Mostrar o valor e a descrição de um contador", "Listar os contadores daqui", "Aumentar um contador em um", "Diminuir um contador em um", "Nome do contador (apenas letras e números)", "Descrição opcional do contador", "Novo nome do contador (apenas letras e números)"],
  ro: ["Creează un contor sau restaurează unul eliminat", "Elimină un contor fără a-i pierde valoarea", "Redenumește un contor", "Arată valoarea și descrierea unui contor", "Listează contoarele de aici", "Mărește un contor cu unu", "Micșorează un contor cu unu", "Numele contorului (doar litere și cifre)", "Descriere opțională a contorului", "Noul nume al contorului (doar litere și cifre)"],
  fi: ["Luo laskuri tai palauta poistettu laskuri", "Poista laskuri säilyttäen sen arvo", "Nimeä laskuri uudelleen", "Näytä laskurin arvo ja kuvaus", "Listaa tämän paikan laskurit", "Kasvata laskuria yhdellä", "Pienennä laskuria yhdellä", "Laskurin nimi (vain kirjaimet ja numerot)", "Laskurin valinnainen kuvaus", "Laskurin uusi nimi (vain kirjaimet ja numerot)"],
  "sv-SE": ["Skapa en räknare eller återställ en borttagen räknare", "Ta bort en räknare utan att förlora värdet", "Byt namn på en räknare", "Visa en räknares värde och beskrivning", "Lista räknarna här", "Öka en räknare med ett", "Minska en räknare med ett", "Räknarens namn (bara bokstäver och siffror)", "Valfri beskrivning av räknaren", "Räknarens nya namn (bara bokstäver och siffror)"],
  vi: ["Tạo bộ đếm hoặc khôi phục bộ đếm đã xóa", "Xóa bộ đếm mà không mất giá trị", "Đổi tên bộ đếm", "Xem giá trị và mô tả của bộ đếm", "Liệt kê các bộ đếm ở đây", "Tăng bộ đếm lên một", "Giảm bộ đếm đi một", "Tên bộ đếm (chỉ chữ cái và chữ số)", "Mô tả tùy chọn cho bộ đếm", "Tên mới của bộ đếm (chỉ chữ cái và chữ số)"],
  tr: ["Sayaç oluştur veya kaldırılmış bir sayacı geri getir", "Sayacı değerini kaybetmeden kaldır", "Bir sayacı yeniden adlandır", "Bir sayacın değerini ve açıklamasını göster", "Buradaki sayaçları listele", "Bir sayacı bir artır", "Bir sayacı bir azalt", "Sayaç adı (yalnızca harf ve rakam)", "Sayaç için isteğe bağlı açıklama", "Yeni sayaç adı (yalnızca harf ve rakam)"],
  cs: ["Vytvořit počítadlo nebo obnovit odstraněné", "Odstranit počítadlo bez ztráty jeho hodnoty", "Přejmenovat počítadlo", "Zobrazit hodnotu a popis počítadla", "Vypsat zdejší počítadla", "Zvýšit počítadlo o jedna", "Snížit počítadlo o jedna", "Název počítadla (pouze písmena a číslice)", "Volitelný popis počítadla", "Nový název počítadla (pouze písmena a číslice)"],
  el: ["Δημιουργία μετρητή ή επαναφορά καταργημένου μετρητή", "Κατάργηση μετρητή χωρίς απώλεια της τιμής του", "Μετονομασία μετρητή", "Προβολή τιμής και περιγραφής μετρητή", "Λίστα των μετρητών εδώ", "Αύξηση μετρητή κατά ένα", "Μείωση μετρητή κατά ένα", "Όνομα μετρητή (μόνο γράμματα και ψηφία)", "Προαιρετική περιγραφή του μετρητή", "Νέο όνομα μετρητή (μόνο γράμματα και ψηφία)"],
  bg: ["Създаване на брояч или възстановяване на премахнат", "Премахване на брояч без загуба на стойността му", "Преименуване на брояч", "Показване на стойността и описанието на брояч", "Списък на броячите тук", "Увеличаване на брояч с едно", "Намаляване на брояч с едно", "Име на брояча (само букви и цифри)", "Незадължително описание на брояча", "Ново име на брояча (само букви и цифри)"],
  ru: ["Создать счётчик или восстановить удалённый", "Удалить счётчик с сохранением его значения", "Переименовать счётчик", "Показать значение и описание счётчика", "Показать список счётчиков здесь", "Увеличить счётчик на один", "Уменьшить счётчик на один", "Название счётчика (только буквы и цифры)", "Необязательное описание счётчика", "Новое название счётчика (только буквы и цифры)"],
  uk: ["Створити лічильник або відновити видалений", "Видалити лічильник зі збереженням його значення", "Перейменувати лічильник", "Показати значення й опис лічильника", "Показати список лічильників тут", "Збільшити лічильник на один", "Зменшити лічильник на один", "Назва лічильника (лише літери та цифри)", "Необов'язковий опис лічильника", "Нова назва лічильника (лише літери та цифри)"],
  hi: ["काउंटर बनाएँ या हटाया गया काउंटर बहाल करें", "मान खोए बिना काउंटर हटाएँ", "काउंटर का नाम बदलें", "काउंटर का मान और विवरण दिखाएँ", "यहाँ के काउंटरों की सूची दिखाएँ", "काउंटर को एक बढ़ाएँ", "काउंटर को एक घटाएँ", "काउंटर का नाम (केवल अक्षर और अंक)", "काउंटर का वैकल्पिक विवरण", "काउंटर का नया नाम (केवल अक्षर और अंक)"],
  th: ["สร้างตัวนับหรือกู้คืนตัวนับที่ลบไป", "ลบตัวนับโดยเก็บค่าเดิมไว้", "เปลี่ยนชื่อตัวนับ", "แสดงค่าและคำอธิบายของตัวนับ", "แสดงรายการตัวนับที่นี่", "เพิ่มค่าตัวนับหนึ่ง", "ลดค่าตัวนับหนึ่ง", "ชื่อตัวนับ (เฉพาะตัวอักษรและตัวเลข)", "คำอธิบายตัวนับ (ไม่บังคับ)", "ชื่อตัวนับใหม่ (เฉพาะตัวอักษรและตัวเลข)"],
  "zh-CN": ["创建计数器或恢复已删除的计数器", "删除计数器并保留其数值", "重命名计数器", "显示计数器的数值和描述", "列出此处的计数器", "将计数器加一", "将计数器减一", "计数器名称（仅限字母和数字）", "计数器的可选描述", "新的计数器名称（仅限字母和数字）"],
  ja: ["カウンターを作成、または削除済みのカウンターを復元", "値を保持してカウンターを削除", "カウンターの名前を変更", "カウンターの値と説明を表示", "ここのカウンターを一覧表示", "カウンターを1増やす", "カウンターを1減らす", "カウンター名（英数字のみ）", "カウンターの説明（省略可）", "新しいカウンター名（英数字のみ）"],
  "zh-TW": ["建立計數器或還原已刪除的計數器", "刪除計數器並保留其數值", "重新命名計數器", "顯示計數器的數值和說明", "列出此處的計數器", "將計數器加一", "將計數器減一", "計數器名稱（僅限字母和數字）", "計數器的選填說明", "新的計數器名稱（僅限字母和數字）"],
  ko: ["카운터를 만들거나 삭제한 카운터 복원", "값을 유지하면서 카운터 삭제", "카운터 이름 변경", "카운터의 값과 설명 표시", "이곳의 카운터 목록 표시", "카운터를 1 증가", "카운터를 1 감소", "카운터 이름 (영문자와 숫자만)", "카운터 설명 (선택 사항)", "새 카운터 이름 (영문자와 숫자만)"],
} satisfies Record<"en" | TranslatedLocale, TranslationRow>;
function column(index: number): LocalizedString {
  return Object.fromEntries(Object.entries(rows).map(([locale, row]) => [locale, row[index]!])) as LocalizedString;
}
export const STR = {
  "cmd.addcounter.desc": column(0), "cmd.addcounter.opt.name.desc": column(7), "cmd.addcounter.opt.description.desc": column(8),
  "cmd.removecounter.desc": column(1), "cmd.removecounter.opt.name.desc": column(7),
  "cmd.renamecounter.desc": column(2), "cmd.renamecounter.opt.name.desc": column(7), "cmd.renamecounter.opt.new_name.desc": column(9),
  "cmd.counter.desc": column(3), "cmd.counter.opt.name.desc": column(7),
  "cmd.counters.desc": column(4),
  "cmd.increment.desc": column(5), "cmd.increment.opt.name.desc": column(7),
  "cmd.decrement.desc": column(6), "cmd.decrement.opt.name.desc": column(7),
};
