import type { LocalizedString, TranslatedLocale } from "./locales";
// One row per locale. Columns, by index:
//   0 addcounter  1 removecounter  2 renamecounter  3 counter  4 counters  5 increment  6 decrement
//   7 `name` option  8 `description` option  9 `new_name` option
// Keep every cell ≤ 100 characters (Discord's limit; the validator enforces it).
type TranslationRow = readonly [string, string, string, string, string, string, string, string, string, string];
const rows = {
  en: ["Create a counter or restore a removed counter", "Remove a counter without losing its count", "Rename a counter", "Show a counter's count and description", "List the counters here", "Increase a counter by one", "Decrease a counter by one", "Counter name (letters, digits, and spaces)", "Optional description for the counter", "New counter name (letters, digits, and spaces)"],
  id: ["Buat penghitung atau pulihkan yang dihapus", "Hapus penghitung tanpa kehilangan nilainya", "Ubah nama penghitung", "Lihat nilai dan deskripsi penghitung", "Daftar penghitung di sini", "Tambah nilai penghitung satu", "Kurangi nilai penghitung satu", "Nama penghitung (huruf, angka, dan spasi)", "Deskripsi opsional penghitung", "Nama baru penghitung (huruf, angka, dan spasi)"],
  da: ["Opret en tæller eller gendan en fjernet tæller", "Fjern en tæller uden at miste dens tal", "Omdøb en tæller", "Vis en tællers tal og beskrivelse", "Vis tællerne her", "Forøg en tæller med én", "Formindsk en tæller med én", "Tællernavn (bogstaver, tal og mellemrum)", "Valgfri beskrivelse af tælleren", "Nyt tællernavn (bogstaver, tal og mellemrum)"],
  de: ["Einen Zähler erstellen oder wiederherstellen", "Einen Zähler entfernen und seinen Stand behalten", "Einen Zähler umbenennen", "Zählerstand und Beschreibung anzeigen", "Die Zähler hier auflisten", "Einen Zähler um eins erhöhen", "Einen Zähler um eins verringern", "Zählername (Buchstaben, Ziffern und Leerzeichen)", "Optionale Beschreibung des Zählers", "Neuer Zählername (Buchstaben, Ziffern und Leerzeichen)"],
  "es-ES": ["Crear un contador o restaurar uno eliminado", "Eliminar un contador sin perder su valor", "Cambiar el nombre de un contador", "Mostrar el valor y la descripción de un contador", "Listar los contadores de aquí", "Aumentar un contador en uno", "Disminuir un contador en uno", "Nombre del contador (letras, números y espacios)", "Descripción opcional del contador", "Nuevo nombre del contador (letras, números y espacios)"],
  "es-419": ["Crear un contador o restaurar uno eliminado", "Eliminar un contador sin perder su valor", "Cambiar el nombre de un contador", "Mostrar el valor y la descripción de un contador", "Listar los contadores de aquí", "Incrementar un contador en uno", "Reducir un contador en uno", "Nombre del contador (letras, números y espacios)", "Descripción opcional del contador", "Nuevo nombre del contador (letras, números y espacios)"],
  fr: ["Créer un compteur ou restaurer un compteur supprimé", "Supprimer un compteur sans perdre sa valeur", "Renommer un compteur", "Afficher la valeur et la description d'un compteur", "Lister les compteurs ici", "Augmenter un compteur de un", "Diminuer un compteur de un", "Nom du compteur (lettres, chiffres et espaces)", "Description facultative du compteur", "Nouveau nom du compteur (lettres, chiffres et espaces)"],
  hr: ["Stvori brojač ili vrati uklonjeni brojač", "Ukloni brojač bez gubitka njegove vrijednosti", "Preimenuj brojač", "Prikaži vrijednost i opis brojača", "Prikaži ovdašnje brojače", "Povećaj brojač za jedan", "Smanji brojač za jedan", "Naziv brojača (slova, znamenke i razmaci)", "Neobavezan opis brojača", "Novi naziv brojača (slova, znamenke i razmaci)"],
  it: ["Crea un contatore o ripristinane uno rimosso", "Rimuovi un contatore senza perderne il valore", "Rinomina un contatore", "Mostra il valore e la descrizione di un contatore", "Elenca i contatori qui", "Aumenta un contatore di uno", "Diminuisci un contatore di uno", "Nome del contatore (lettere, cifre e spazi)", "Descrizione facoltativa del contatore", "Nuovo nome del contatore (lettere, cifre e spazi)"],
  lt: ["Sukurti skaitiklį arba atkurti pašalintą skaitiklį", "Pašalinti skaitiklį neprarandant jo reikšmės", "Pervadinti skaitiklį", "Rodyti skaitiklio reikšmę ir aprašą", "Rodyti čia esančius skaitiklius", "Padidinti skaitiklį vienetu", "Sumažinti skaitiklį vienetu", "Skaitiklio pavadinimas (raidės, skaitmenys ir tarpai)", "Neprivalomas skaitiklio aprašas", "Naujas skaitiklio pavadinimas (raidės, skaitmenys ir tarpai)"],
  hu: ["Számláló létrehozása vagy eltávolított számláló visszaállítása", "Számláló eltávolítása az értéke megőrzésével", "Számláló átnevezése", "Számláló értékének és leírásának megjelenítése", "Az itteni számlálók listázása", "Számláló növelése eggyel", "Számláló csökkentése eggyel", "Számláló neve (betűk, számjegyek és szóközök)", "A számláló nem kötelező leírása", "Számláló új neve (betűk, számjegyek és szóközök)"],
  nl: ["Maak een teller of herstel een verwijderde teller", "Verwijder een teller zonder de stand te verliezen", "Hernoem een teller", "Toon de stand en beschrijving van een teller", "Toon de tellers hier", "Verhoog een teller met één", "Verlaag een teller met één", "Tellernaam (letters, cijfers en spaties)", "Optionele beschrijving van de teller", "Nieuwe tellernaam (letters, cijfers en spaties)"],
  no: ["Opprett en teller eller gjenopprett en fjernet teller", "Fjern en teller uten å miste verdien", "Gi en teller nytt navn", "Vis en tellers verdi og beskrivelse", "Vis tellerne her", "Øk en teller med én", "Reduser en teller med én", "Tellernavn (bokstaver, tall og mellomrom)", "Valgfri beskrivelse av telleren", "Nytt tellernavn (bokstaver, tall og mellomrom)"],
  pl: ["Utwórz licznik lub przywróć usunięty licznik", "Usuń licznik bez utraty jego wartości", "Zmień nazwę licznika", "Pokaż wartość i opis licznika", "Wyświetl tutejsze liczniki", "Zwiększ licznik o jeden", "Zmniejsz licznik o jeden", "Nazwa licznika (litery, cyfry i spacje)", "Opcjonalny opis licznika", "Nowa nazwa licznika (litery, cyfry i spacje)"],
  "pt-BR": ["Criar um contador ou restaurar um removido", "Remover um contador sem perder seu valor", "Renomear um contador", "Mostrar o valor e a descrição de um contador", "Listar os contadores daqui", "Aumentar um contador em um", "Diminuir um contador em um", "Nome do contador (letras, números e espaços)", "Descrição opcional do contador", "Novo nome do contador (letras, números e espaços)"],
  ro: ["Creează un contor sau restaurează unul eliminat", "Elimină un contor fără a-i pierde valoarea", "Redenumește un contor", "Arată valoarea și descrierea unui contor", "Listează contoarele de aici", "Mărește un contor cu unu", "Micșorează un contor cu unu", "Numele contorului (litere, cifre și spații)", "Descriere opțională a contorului", "Noul nume al contorului (litere, cifre și spații)"],
  fi: ["Luo laskuri tai palauta poistettu laskuri", "Poista laskuri säilyttäen sen arvo", "Nimeä laskuri uudelleen", "Näytä laskurin arvo ja kuvaus", "Listaa tämän paikan laskurit", "Kasvata laskuria yhdellä", "Pienennä laskuria yhdellä", "Laskurin nimi (kirjaimet, numerot ja välilyönnit)", "Laskurin valinnainen kuvaus", "Laskurin uusi nimi (kirjaimet, numerot ja välilyönnit)"],
  "sv-SE": ["Skapa en räknare eller återställ en borttagen räknare", "Ta bort en räknare utan att förlora värdet", "Byt namn på en räknare", "Visa en räknares värde och beskrivning", "Lista räknarna här", "Öka en räknare med ett", "Minska en räknare med ett", "Räknarens namn (bokstäver, siffror och mellanslag)", "Valfri beskrivning av räknaren", "Räknarens nya namn (bokstäver, siffror och mellanslag)"],
  vi: ["Tạo bộ đếm hoặc khôi phục bộ đếm đã xóa", "Xóa bộ đếm mà không mất giá trị", "Đổi tên bộ đếm", "Xem giá trị và mô tả của bộ đếm", "Liệt kê các bộ đếm ở đây", "Tăng bộ đếm lên một", "Giảm bộ đếm đi một", "Tên bộ đếm (chữ cái, chữ số và dấu cách)", "Mô tả tùy chọn cho bộ đếm", "Tên mới của bộ đếm (chữ cái, chữ số và dấu cách)"],
  tr: ["Sayaç oluştur veya kaldırılmış bir sayacı geri getir", "Sayacı değerini kaybetmeden kaldır", "Bir sayacı yeniden adlandır", "Bir sayacın değerini ve açıklamasını göster", "Buradaki sayaçları listele", "Bir sayacı bir artır", "Bir sayacı bir azalt", "Sayaç adı (harf, rakam ve boşluk)", "Sayaç için isteğe bağlı açıklama", "Yeni sayaç adı (harf, rakam ve boşluk)"],
  cs: ["Vytvořit počítadlo nebo obnovit odstraněné", "Odstranit počítadlo bez ztráty jeho hodnoty", "Přejmenovat počítadlo", "Zobrazit hodnotu a popis počítadla", "Vypsat zdejší počítadla", "Zvýšit počítadlo o jedna", "Snížit počítadlo o jedna", "Název počítadla (písmena, číslice a mezery)", "Volitelný popis počítadla", "Nový název počítadla (písmena, číslice a mezery)"],
  el: ["Δημιουργία μετρητή ή επαναφορά καταργημένου μετρητή", "Κατάργηση μετρητή χωρίς απώλεια της τιμής του", "Μετονομασία μετρητή", "Προβολή τιμής και περιγραφής μετρητή", "Λίστα των μετρητών εδώ", "Αύξηση μετρητή κατά ένα", "Μείωση μετρητή κατά ένα", "Όνομα μετρητή (γράμματα, ψηφία και κενά)", "Προαιρετική περιγραφή του μετρητή", "Νέο όνομα μετρητή (γράμματα, ψηφία και κενά)"],
  bg: ["Създаване на брояч или възстановяване на премахнат", "Премахване на брояч без загуба на стойността му", "Преименуване на брояч", "Показване на стойността и описанието на брояч", "Списък на броячите тук", "Увеличаване на брояч с едно", "Намаляване на брояч с едно", "Име на брояча (букви, цифри и интервали)", "Незадължително описание на брояча", "Ново име на брояча (букви, цифри и интервали)"],
  ru: ["Создать счётчик или восстановить удалённый", "Удалить счётчик с сохранением его значения", "Переименовать счётчик", "Показать значение и описание счётчика", "Показать список счётчиков здесь", "Увеличить счётчик на один", "Уменьшить счётчик на один", "Название счётчика (буквы, цифры и пробелы)", "Необязательное описание счётчика", "Новое название счётчика (буквы, цифры и пробелы)"],
  uk: ["Створити лічильник або відновити видалений", "Видалити лічильник зі збереженням його значення", "Перейменувати лічильник", "Показати значення й опис лічильника", "Показати список лічильників тут", "Збільшити лічильник на один", "Зменшити лічильник на один", "Назва лічильника (літери, цифри та пробіли)", "Необов'язковий опис лічильника", "Нова назва лічильника (літери, цифри та пробіли)"],
  hi: ["काउंटर बनाएँ या हटाया गया काउंटर बहाल करें", "मान खोए बिना काउंटर हटाएँ", "काउंटर का नाम बदलें", "काउंटर का मान और विवरण दिखाएँ", "यहाँ के काउंटरों की सूची दिखाएँ", "काउंटर को एक बढ़ाएँ", "काउंटर को एक घटाएँ", "काउंटर का नाम (अक्षर, अंक और स्पेस)", "काउंटर का वैकल्पिक विवरण", "काउंटर का नया नाम (अक्षर, अंक और स्पेस)"],
  th: ["สร้างตัวนับหรือกู้คืนตัวนับที่ลบไป", "ลบตัวนับโดยเก็บค่าเดิมไว้", "เปลี่ยนชื่อตัวนับ", "แสดงค่าและคำอธิบายของตัวนับ", "แสดงรายการตัวนับที่นี่", "เพิ่มค่าตัวนับหนึ่ง", "ลดค่าตัวนับหนึ่ง", "ชื่อตัวนับ (ตัวอักษร ตัวเลข และช่องว่าง)", "คำอธิบายตัวนับ (ไม่บังคับ)", "ชื่อตัวนับใหม่ (ตัวอักษร ตัวเลข และช่องว่าง)"],
  "zh-CN": ["创建计数器或恢复已删除的计数器", "删除计数器并保留其数值", "重命名计数器", "显示计数器的数值和描述", "列出此处的计数器", "将计数器加一", "将计数器减一", "计数器名称（字母、数字和空格）", "计数器的可选描述", "新的计数器名称（字母、数字和空格）"],
  ja: ["カウンターを作成、または削除済みのカウンターを復元", "値を保持してカウンターを削除", "カウンターの名前を変更", "カウンターの値と説明を表示", "ここのカウンターを一覧表示", "カウンターを1増やす", "カウンターを1減らす", "カウンター名（英数字とスペース）", "カウンターの説明（省略可）", "新しいカウンター名（英数字とスペース）"],
  "zh-TW": ["建立計數器或還原已刪除的計數器", "刪除計數器並保留其數值", "重新命名計數器", "顯示計數器的數值和說明", "列出此處的計數器", "將計數器加一", "將計數器減一", "計數器名稱（字母、數字和空格）", "計數器的選填說明", "新的計數器名稱（字母、數字和空格）"],
  ko: ["카운터를 만들거나 삭제한 카운터 복원", "값을 유지하면서 카운터 삭제", "카운터 이름 변경", "카운터의 값과 설명 표시", "이곳의 카운터 목록 표시", "카운터를 1 증가", "카운터를 1 감소", "카운터 이름 (영문자, 숫자, 공백)", "카운터 설명 (선택 사항)", "새 카운터 이름 (영문자, 숫자, 공백)"],
} satisfies Record<"en" | TranslatedLocale, TranslationRow>;
function column(index: number): LocalizedString {
  return Object.fromEntries(Object.entries(rows).map(([locale, row]) => [locale, row[index]!])) as LocalizedString;
}
export const STR = {
  "cmd.addcounter.desc": column(0), "cmd.addcounter.opt.name.desc": column(7), "cmd.addcounter.opt.description.desc": column(8),
  "cmd.removecounter.desc": column(1), "cmd.removecounter.opt.name.desc": column(7),
  "cmd.renamecounter.desc": column(2), "cmd.renamecounter.opt.name.desc": column(7), "cmd.renamecounter.opt.new_name.desc": column(9),
  "cmd.counter.desc": column(3), "cmd.counter.opt.name.desc": column(7),
  "cmd.counters.desc": column(4),
  "cmd.increment.desc": column(5), "cmd.increment.opt.name.desc": column(7),
  "cmd.decrement.desc": column(6), "cmd.decrement.opt.name.desc": column(7),
};
